apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: shopmicro
  labels:
    role: prometheus-rulefiles
data:
  alerts.yaml: |
    groups:
    - name: application-alerts
      rules:
      - alert: HighErrorRate
        expr: sum(rate(http_server_requests_total{status_code=~"5.."}[5m])) / sum(rate(http_server_requests_total[5m])) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High Error Rate detected"
          description: "Error rate is above 10% for the last 5 minutes."
      
      - alert: HighLatency
        expr: histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket[5m])) by (le, service_name)) > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High P95 Latency"
          description: "P95 latency is above 500ms for service {{ $labels.service_name }}"
